### ISSUE TITLE
Coordinate error when zoom level > 9

### ISSUE THREAD

**Issue by mkapal** [kontrollanten/lantmateriet-leaflet#1]
When I zoom in more than up to level 9, I get this error:
`TypeError: coordinates must be finite numbers`

For my needs, I need to be able to zoom up to level 13. If it is possible, how do I edit the configuration to make it work?

**Comment by kontrollanten** [comment]
As far as I remember you have to by a license to zoom beyond level 9. It was pretty hard to find information regarding that though. Maybe the easiest way to find an answer is to e-mail geodatasupport@lm.se and ask.

**Comment by mkapal** [comment]
Thanks for the explanation.
What I'm trying to achieve is to use the same map as they use here https://kso.etjanster.lantmateriet.se/.
I also tried using the same API requests as they do on their page but the zoom problem was still there, so I guess it must be a licensing issue.

**Comment by kontrollanten** [comment]
Okay. If you find the solution/answer, please let me know and I'll add information in the README.
